version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '21:00'
      timezone: 'Europe/Amsterdam'
    labels:
      - infrastructure

  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '21:00'
      timezone: 'Europe/Amsterdam'
    target-branch: main
    commit-message:
      prefix: "ğŸ³ "
    labels:
      - infrastructure
      - docker-update
    ignore:
      - dependency-name: node
        versions:
          - '>= 23'

  - package-ecosystem: docker
    directory: '/ci/tailormap-embed-test/'
    schedule:
      interval: weekly
      day: monday
      time: '21:00'
      timezone: 'Europe/Amsterdam'
    target-branch: main
    commit-message:
      prefix: "ğŸ³ "
    labels:
      - infrastructure
      - docker-update

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: '21:00'
      timezone: 'Europe/Amsterdam'
    commit-message:
      prefix: "â›“ï¸â€ğŸ’¥ "
    labels:
      - breaking
      - docker-update
      - infrastructure
